#!/bin/sh

BAT_META=/sys/class/power_supply/BAT1

CURR_CAP=$(cat $BAT_META/capacity)
CURR_STATUS=$(cat $BAT_META/status)

RECOMMENDED_MIN=25
CLASS="battery"

if [ $CURR_CAP -le $RECOMMENDED_MIN -a $CURR_STATUS == "Discharging" ]; then
  CLASS="battery-low";
fi

echo "{ \"cap\": $CURR_CAP, \"class\": \"$CLASS\", \"status\": \"$CURR_STATUS\" }"

