#!/usr/bin/bash

icon=/usr/share/transmission/public_html/images/favicon.png

pgrep -xf "transmission-daemon" > /dev/null
daemon_running=$?

if [ $daemon_running -ne 0 ]; then
    notify-send \
      -i $icon \
      -a Transmission \
      "Transmission Daemon" "Daemon is not running"
    exit 1
fi

transmission-remote --add "$@" && \
  notify-send \
  -i $icon \
  -a Transmission \
  "Transmission Daemon" "Torrent added for downloading"
