{
  imports = [
    ./bootloader.nix
    ./env.nix
    ./users.nix
    ./networkmanager.nix
    ./hyprland.nix
    ./gc.nix
    ./ld.nix
    ./xdg.nix
    ./dbus.nix
    ./bluetooth.nix
    ./logind.nix
    ./sleep.nix
    ./fprint.nix
    ./polkit.nix
    ./security.nix
    ./opengl.nix
  ];
}
