#!/bin/bash

sink=$(pactl info | grep "Default Sink" | cut -f3 -d" ")
status=$(pactl list sinks | grep -A 10 $sink | grep "Mute" | cut -f2 -d":" | tr -d '[:blank:]')

text="%{F#cdd6f4}"
red="%{F#f38ba8}"
mauve="%{F#cba6f7}"

vol_icon="%{T2}"
vol_text="%{T-}$text"

if [ "$status" = "no" ]; then
  volume=$(pactl list sinks | grep -m 1 -A 10 $sink | grep -m 1 "Volume" | grep -oP '[0-9]+(?=%)' | awk '{sum+=$1} END {print sum/NR}')
  vol_icon="$mauve$vol_icon"
  vol_text=" $vol_text$volume%"
else
  vol_icon="$red$vol_icon"
fi

vol="%{A:pactl set-sink-mute $sink toggle:}$vol_icon%{A}$vol_text"

source=$(pactl info | grep "Default Source" | cut -f3 -d" ")
status=$(pactl list sources | grep -A 10 $source | grep "Mute" | cut -f2 -d":" | tr -d '[:blank:]')

mic="%{T2}"

if [ "$status" = "yes" ]; then
    mic="$mic$red"
else
    mic="$mic$mauve"
fi

mic="%{A:pactl set-source-mute $source toggle:}$mic%{A}"

echo "$vol  $mic"
