#!/bin/bash

text="%{F#cdd6f4}"
red="%{F#f38ba8}"

if [ "$1" == "--status" ]; then
  curr=$(sudo wg show | grep "interface:" | cut -f2 -d" ")

  output="%{T2}"

  if [ -z "$curr" ]; then
    output="$output$red"
  else
    output="%{A:sudo wg-quick down $curr:}$output %{T-}$text$curr%{A}"
  fi

  echo $output

  exit 0
fi

interfaces=($(ls /etc/wireguard/ | sed 's/.conf//g'))

selected_interface=$(printf '%s\n' "${interfaces[@]/$'\n'/}" | dmenu -c -l 10)

sudo wg-quick up $selected_interface
